### ISSUE TITLE
Facebook making Messenger mandatory

### ISSUE THREAD

**Issue by mycomop** [velazcod/Tinfoil-Facebook#84] opened 2016-04-15 14:26 UTC
As of yesterday (4/14/16), Facebook appears to be blocking access to messages via any means other than its own laggy, battery-sucking, Messenger app.  Is there any hope of overcoming/circumventing this?

**Comment by diederikdehaas** [comment] 2016-04-15 14:33
I have configured it to use FB .union address through Orbot (Tor for Android) and it seems to still work here.
See https://github.com/velazcod/Tinfoil-Facebook/issues/35 for details on that

**Comment by gdkrmr** [comment] 2016-04-17 06:51
For me it crashes just the same if i try to access the messages over the .onion site. What works is the 'basic site' and the mobile site in Firefox, maybe it is user agent thing.

**Comment by mikebabb** [comment] 2016-04-18 09:07
The developer of another Facebook wrapper app has found a workaround that loads the interface of messenger.com in the messages tab of the app rather than redirecting to the Play Store to download Facebook's native one, detailed [here]https://www.reddit.com/r/Android/comments/4f5pcg/psa_facebook_is_planning_on_removing/d26fm72). Would it be possible for Tinfoil to implement something similar maybe?

**Comment by abdullahhhhh** [comment] 2016-05-05 00:59
Related/duplicate of #83? App crashes now when accessing messages unless using the desktop or basic versions.

**Comment by gsurrel** [comment] 2016-06-01 10:02
I just had this behavior today, so I fixed it by pretending to have Messenger with [Messenger Bypasser](https://github.com/gsurrel/MessengerBypasser)

Basically, it works well except for some group conversations where FB wants to start an intent which is opened by Tinfoil : "Impossible to load the webpage intent://groupthreadfbid/…  net::ERR_UNKNOWN_URL_SCHEME". Maybe [that could be a fix](https://stackoverflow.com/questions/3564393/launching-my-app-using-the-intent-uri) for Tinfoil.

**Comment by jfmcbrayer** [comment] 2016-06-01 12:23
I've found that the messages tab in the Facebook mobile site works on Firefox for Android. Getting messages working in Tinfoil could be as simple as spoofing the user agent.

**Comment by gjedeer** [comment] 2016-07-07 07:18
I've read reports that spoofing UA so that it's not one of {Android, iOS} makes the messaging tab work.

**Comment by kofalt** [comment] 2016-07-07 15:30
This repo hasn't seen an update for over a year, with [no recent activity](https://github.com/velazcod?tab=activity) by the maintainer, so I'm assuming it's not currently maintained. Is anyone working on a fork of this, perchance? It would be great to have a functional app again.

**Comment by Natureshadow** [comment] 2016-10-10 16:19
Setting the site version to minimal in settings is a workaround.

**Comment by syskill** [comment] 2016-12-27 02:21
Natureshadow is correct. Messaging is unusable in the mobile site (because Facebook only presents the user with a button to install the app) but works fine in the basic or desktop sites.

I suggest that the app use the basic site instead of the mobile site for messaging whenever the mobile/desktop site preference is set to "auto".

**Comment by prati0100** [comment] 2016-12-27 13:18
For some reason messaging works perfectly fine on my phone. I don't have to use the basic or desktop site? Anyone have any idea why it works for some and doesn't for others

**Comment by Krawei** [comment] 2017-02-13 23:11
Any updates here? It seems that there's no update for this app anymore. Is this project discontinued?

**Closed** 2017-02-21 00:58 UTC
